version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - composer install

  build:
    commands:
      - make test
      - echo "CODEBUILD_SRC_DIR:" ${CODEBUILD_SRC_DIR}
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION:" ${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo "CODEBUILD_SOURCE_VERSION:" ${CODEBUILD_SOURCE_VERSION}
      - echo "CODEBUILD_WEBHOOK_PREV_COMMIT:" ${CODEBUILD_WEBHOOK_PREV_COMMIT}
      - echo "CODEBUILD_WEBHOOK_BASE_REF:" ${CODEBUILD_WEBHOOK_BASE_REF}
      - echo "CODEBUILD_WEBHOOK_HEAD_REF:" ${CODEBUILD_WEBHOOK_HEAD_REF}
      - echo "CODEBUILD_WEBHOOK_EVENT:" ${CODEBUILD_WEBHOOK_EVENT}
      - echo "CODEBUILD_WEBHOOK_MERGE_COMMIT:" ${CODEBUILD_WEBHOOK_MERGE_COMMIT}
      - echo "CODEBUILD_WEBHOOK_TRIGGER:" ${CODEBUILD_WEBHOOK_TRIGGER}
      - ls -al ${CODEBUILD_SRC_DIR}/vendor
      - ls -al /root/.composer/cache/files

cache:
  paths:
    - ${CODEBUILD_SRC_DIR}/vendor
    - /root/.composer/cache/files

reports:
  phpunit-report:
    files:
      - codebuild/reports.xml
    file-format: JunitXml
