version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - ls -al
      - cd ..
      - ls -al
      - composer install

  build:
    commands:
      - composer run test
